# Generated by Django 5.0.1 on 2024-05-03 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='teoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=1000, null=True)),
                ('prepodID', models.IntegerField(null=True)),
                ('predmet', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='files')),
                ('group', models.CharField(max_length=1500, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('facku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tea.faa')),
            ],
        ),
        migrations.CreateModel(
            name='prepod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('mail', models.CharField(max_length=150, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tea.faa')),
            ],
        ),
        migrations.CreateModel(
            name='stud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('mail', models.CharField(max_length=15, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('groupe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tea.group')),
            ],
        ),
    ]
