# Generated by Django 5.0.1 on 2024-03-29 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0002_fackulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='faa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='fackulty',
        ),
        migrations.RemoveField(
            model_name='prepod',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stud',
            name='user',
        ),
        migrations.AddField(
            model_name='prepod',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='prepod',
            name='surname',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='stud',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='stud',
            name='surname',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='prepod',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tea.faa'),
        ),
        migrations.AlterField(
            model_name='stud',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tea.faa'),
        ),
    ]
