# Generated by Django 5.0.3 on 2024-04-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0007_teoria_docfile_alter_teoria_name_alter_teoria_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prepod',
            old_name='surname',
            new_name='mail',
        ),
        migrations.AddField(
            model_name='prepod',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prepod',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
