# Generated by Django 5.0.3 on 2024-04-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0008_rename_surname_prepod_mail_prepod_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepod',
            name='faculty',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
