# Generated by Django 5.0.3 on 2024-04-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0009_alter_prepod_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stud',
            old_name='surname',
            new_name='mail',
        ),
        migrations.RemoveField(
            model_name='stud',
            name='faculty',
        ),
        migrations.AddField(
            model_name='prepod',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stud',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stud',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stud',
            name='group',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stud',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
