# Generated by Django 5.0.1 on 2024-04-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0010_rename_surname_stud_mail_remove_stud_faculty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='osenITH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_an', models.IntegerField()),
                ('diskr_mat', models.IntegerField()),
                ('an_gem', models.IntegerField()),
                ('yaz_prog', models.IntegerField()),
                ('alg', models.IntegerField()),
                ('lin_al', models.IntegerField()),
            ],
        ),
    ]
