# Generated by Django 5.0.1 on 2024-04-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0013_alter_stud_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud',
            name='url',
            field=models.URLField(blank=True, max_length=150, unique=True),
        ),
    ]
