# Generated by Django 5.0.1 on 2024-04-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0014_alter_stud_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stud',
            name='url',
        ),
        migrations.AddField(
            model_name='stud',
            name='url_osen',
            field=models.URLField(max_length=150, null=True),
        ),
    ]
